In [3]:
values = [2,3,8]
result = []
for x in values:
    result.append(2.1 * x)

result

[4.2, 6.300000000000001, 16.8]

In [4]:
import numpy as np
a = np.array([2,3,8])
2.1 * a

array([ 4.2,  6.3, 16.8])

In [5]:
a * a

array([ 4,  9, 64])

In [6]:
a ** 2

array([ 4,  9, 64], dtype=int32)

In [10]:
np.dot(a,a) #(2*2)+(3*3)+(8*8)

77

## Shape

In [11]:
import numpy as np
a = np.array([2, 3, 8])
a.shape                   # To get the shape of an array, we use shape:

(3,)

In [12]:
b = np.array([
    [2, 3, 8],
    [4, 5, 6]
])
b.shape

(2, 3)

## Slicing

In [18]:
a = np.array([2, 3, 8])
print (a[2])
a[1:]

8


array([3, 8])

In [22]:
b = np.array([
    [2, 3, 8], # fila 0 columnas 0,1,2
    [4, 5, 6]  # fila 1 columnas 0,1,2
])
print (b[1])
print (b[1][2]) # Podemos abreviar como:
print (b[1, 2])

[4 5 6]
6
6


In [21]:
b[:,1] # columna 1 de la matriz

array([3, 5])

## Masking 

In [27]:
a = np.array([230, 10, 284, 39, 76])
cutoff = 200
new_a = []
print (a)
print (a > cutoff)
for x in a:
    if x > cutoff:
        new_a.append(0)
    else:
        new_a.append(x)
a = np.array(new_a)
print (a)

[230  10 284  39  76]
[ True False  True False False]
[ 0 10  0 39 76]


In [29]:
a = np.array([230, 10, 284, 39, 76])
cutoff = 200
a[a > cutoff] = 0                   # resuelve de forma mas rapida el bucle for con a_new
print(a)

[ 0 10  0 39 76]


## Broadcasting 

In [30]:
a = np.array([
    [0, 1],
    [2, 3],
    [4, 5],
    ])
b = np.array([10, 100])
a * b

array([[  0, 100],
       [ 20, 300],
       [ 40, 500]])

In [32]:
c = np.array([
    [0, 1, 2],
    [3, 4, 5],
    ])
b = np.array([10, 100])
c * b                    # ValueError: operands could not be broadcast together with shapes (2,3) (2,)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [33]:
c * b[:, None]

array([[  0,  10,  20],
       [300, 400, 500]])

A good visual description of these rules, together with some advanced broadcasting applications can be found in this
tutorial of Numpy broadcasting rules.

http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc

## dtype

In [34]:
import numpy as np
a = np.array([200], dtype='uint8')
a + a                              # No cabe en el uint8

array([144], dtype=uint8)

In [35]:
import numpy as np
a = np.array([200], dtype='uint16')
a + a

array([400], dtype=uint16)

In [36]:
a = np.array([200], dtype='uint8')
a.astype('uint64')                  # Changing dtype

array([200], dtype=uint64)

Mas info:
https://numpy.org/doc/stable/user/quickstart.html   
    https://numpy.org/doc/stable/reference/arrays.indexing.html   
        http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc